### ISSUE TITLE
Discovery on Android problem?

### ISSUE THREAD

**Issue by valentinarapaj** [tr3v3r/react-native-esc-pos-printer#126]
Hello. I get this error every time I try do discover printers on an android device.

` ERROR  Your app just crashed. See the error below.
com.facebook.react.bridge.ObjectAlreadyConsumedException: Array already consumed
  com.facebook.react.bridge.WritableNativeArray.pushNativeMap(Native Method)
  com.facebook.react.bridge.WritableNativeArray.pushMap(WritableNativeArray.java:57)
  com.reactnativeescposprinter.EscPosPrinterDiscoveryModule$3$1.run(EscPosPrinterDiscoveryModule.java:258)
  android.os.Handler.handleCallback(Handler.java:942)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:226)
  android.os.Looper.loop(Looper.java:313)
  android.app.ActivityThread.main(ActivityThread.java:8775)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by tr3v3r** [comment]
@valentinarapaj  please specify please more details on the environment.
Lib version at list

**Comment by valentinarapaj** [comment]
> @valentinarapaj please specify more details on the environment. Lib version at least

Yes I am sorry. Trying on a Samsung Tablet A7.

I am using the last version API.
`"react-native-esc-pos-printer": "^3.0.2"`

My react-native version
`"react-native": "^0.72.7"`

The error is at line 258 in file /android/src/main/java/com/reactnativeescposprinter/EscPosPrinterDiscoveryModule.java
`mPrinterList.pushMap(printerData);`

I've tried to use the hook and the class, but it seems it's not related to the library itself, but the native module written in Java.

**Comment by tr3v3r** [comment]
@valentinarapaj  Just released 3.0.3 with the fix could you please try it out?

**Comment by valentinarapaj** [comment]
Yes the bug is fixed, thank you very much.

**Comment by valentinarapaj** [comment]
Yes the bug is fixed, thank you very much.

**Comment by Jonyleeson** [comment]
Hi @tr3v3r,

This bug seems to have been reintroduced.

Version used: 4.1.0
Printer: TM-M30II
Problem: application crashes after discovering on android, after initially displaying the printer as detected in bluetooth (I'd guess once the same printer is detected again on LAN). 
I'm guessing the crash is related to discovering multiple printers, as if I disable bluetooth then there is no crash and the printer is detected on LAN.


Commit previously fixing bug:
https://github.com/tr3v3r/react-native-esc-pos-printer/commit/e9276b804c9e221fc2dcf996c668902bf70d405d

Commit re-introducing bug:
https://github.com/tr3v3r/react-native-esc-pos-printer/commit/b5275ae64ca87bc7c9fd3a16bff2f0a73a99ef7b

**Comment by Jonyleeson** [comment]
Just to expand on this:

The error is line 231 of EscPosPrinterDiscoveryModule.java:

`com.facebook.react.bridge.ObjectAlreadyConsumedException: Array already consumed
    at com.facebook.react.bridge.WritableNativeArray.pushNativeMap(WritableNativeArray.java)
    at com.facebook.react.bridge.WritableNativeArray.pushMap(WritableNativeArray.java:57)
    at com.reactnativeescposprinter.EscPosPrinterDiscoveryModule$3$1.run(EscPosPrinterDiscoveryModule.java:231)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8913)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

I'm not an android dev and am not familiar with react native bridge, but I'm guessing you can't push onto a WriteableArray that has already been consumed by react native.
Perhaps a solution could be to maintain an internal list and only send copies to react to be consumed? A cursory glance at the WriteableArray class would suggest something along the lines of:
https://github.com/rushour-io/react-native-esc-pos-printer/commit/90c6fa4513f22d9625c7e1100c8d2cc7a03429a5

I am unable to test today for lack of hardware, but can test tomorrow.

Again I could be completely wrong about this (as I mentioned I have little to no experience with android / react native bridge), but I'd rather share my input and be wrong than keep silent.

**Comment by edvijaka** [comment]
I am experiencing something similar. When trying to discover printers the android app crashed (iOS works fine). Downgrading to version 4.0.0 does not crash the android app but it does return only one printer (I have two on the same LAN network).

**Comment by tr3v3r** [comment]
Just released a new version with the possible fix.
Please check: 4.1.1

Unfortunately, I can't test it right now - so it is on you :D.

Please update here regarding the results.

CC: @edvijaka @Jonyleeson

**Comment by edvijaka** [comment]
@tr3v3r the fix did not work. The error I got ->

`java.lang.IllegalArgumentException: Unknown value type class com.facebook.react.bridge.WritableNativeMap
                                                                                                    	at com.facebook.react.bridge.Arguments.fromList(Arguments.java:275)
                                                                                                    	at com.reactnativeescposprinter.EscPosPrinterDiscoveryModule$3$1.run(EscPosPrinterDiscoveryModule.java:236)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8913)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

**Comment by edvijaka** [comment]
:D will try your version now

**Comment by edvijaka** [comment]
@tr3v3r unfortunately version 4.1.2 also crashes the app.

**Comment by tr3v3r** [comment]
@edvijaka just released 4.1.3 based on your PR.
I bet it'll work

**Comment by tr3v3r** [comment]
Thanks for support

**Comment by Jonyleeson** [comment]
Thanks for the quick fix guys !
