### ISSUE TITLE
Library crashes on x86, missing discover method

### ISSUE THREAD

**Issue by andrioid** [tr3v3r/react-native-esc-pos-printer#25]
**Background:** We're using the library on ARM devices, where it works perfectly. Recently someone dropped an Intel device on my desk and asked me to make it work.

The app runs, and then crashes with `Could not invoke EscPosPrinterDiscovery.discover`.
<details>
  <summary>See Stacktrace</summary>
  
```
10-13 08:37:05.990 30591 30613 E AndroidRuntime: java.lang.RuntimeException: Could not invoke EscPosPrinterDiscovery.discover
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	... 8 more
10-13 08:37:05.990 30591 30613 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.app.release-2/lib/arm/libepos2.so" has unexpected e_machine: 40
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1562)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.epson.epos2.discovery.Discovery.<clinit>(Discovery.java:24)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.epson.epos2.discovery.Discovery.stop(Discovery.java)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.reactnativeescposprinter.EscPosPrinterDiscoveryModule.stopDiscovery(EscPosPrinterDiscoveryModule.java:146)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.reactnativeescposprinter.EscPosPrinterDiscoveryModule.startDiscovery(EscPosPrinterDiscoveryModule.java:157)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	at com.reactnativeescposprinter.EscPosPrinterDiscoveryModule.discover(EscPosPrinterDiscoveryModule.java:256)
10-13 08:37:05.990 30591 30613 E AndroidRuntime: 	... 10 more
```
</details>

What strikes me as weird, is that it is trying to use a library from "/data/app/com.app.release-2/lib/arm/libepos2.so", where it obviously should be using the x86 version of libepos2.so.

Any help would be appreciated.

We're using version 0.14.1, but AFAIK; there hasn't been any changes to the code in question since the release.

**Comment by tr3v3r** [comment]
@andrioid hello! 
For now, actually, I don't have a quick solution for this issue since I don't have enough knowledge in this area. 
I've just made a quick investigation and found a related issue [here](https://stackoverflow.com/questions/43447070/java-lang-unsatisfiedlinkerror-has-unexpected-e-machine-40).

What I can try now: 
Try to reproduce your issue locally and play around a bit with SDK.

It would be nice if you also could do the same

Here the [latest SDK](https://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=6737&scat=61&pcat=52) for android

**Comment by tr3v3r** [comment]
@andrioid Thanks!

Could you please share the exact code that you've changed to make it work? 
Just for other guys )
